### ISSUE TITLE
Attachments don't work on Android devices

### ISSUE THREAD

**Issue by henviale** [katzer/cordova-plugin-email-composer#200]
Hi Team,
I'm trying to get the plugin to work with attachments but I'm having serious problems with Android devices.

Below is the error listing shown by the Android Studio logcat:

`05-02 15:59:00.702 12421-13756/it.zerob.dg W/Bundle: Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a android.text.SpannableStringBuilder.  The default value <null> was returned.
05-02 15:59:00.732 12421-13756/it.zerob.dg W/Bundle: Attempt to cast generated internal exception:
                                                     java.lang.ClassCastException: android.text.SpannableStringBuilder cannot be cast to java.util.ArrayList
                                                         at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1367)
                                                         at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:5240)
                                                         at android.content.Intent.migrateExtraStreamToClipData(Intent.java:7793)
                                                         at android.content.Intent.migrateExtraStreamToClipData(Intent.java:7760)
                                                         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1423)
                                                         at android.app.Activity.startActivityForResult(Activity.java:3532)
                                                         at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:332)
                                                         at android.app.Activity.startActivityForResult(Activity.java:3493)
                                                         at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:65)
                                                         at de.appplant.cordova.emailcomposer.EmailComposer$2.run(EmailComposer.java:127)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                         at java.lang.Thread.run(Thread.java:841)
05-02 15:59:00.732 12421-13756/it.zerob.dg W/Bundle: Key android.intent.extra.HTML_TEXT expected ArrayList<String> but value was a java.lang.String.  The default value <null> was returned.
05-02 15:59:00.752 12421-13756/it.zerob.dg W/Bundle: Attempt to cast generated internal exception:
                                                     java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
                                                         at android.os.Bundle.getStringArrayList(Bundle.java:1345)
                                                         at android.content.Intent.getStringArrayListExtra(Intent.java:5226)
                                                         at android.content.Intent.migrateExtraStreamToClipData(Intent.java:7794)
                                                         at android.content.Intent.migrateExtraStreamToClipData(Intent.java:7760)
                                                         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1423)
                                                         at android.app.Activity.startActivityForResult(Activity.java:3532)
                                                         at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:332)
                                                         at android.app.Activity.startActivityForResult(Activity.java:3493)
                                                         at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:65)
                                                         at de.appplant.cordova.emailcomposer.EmailComposer$2.run(EmailComposer.java:127)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                         at java.lang.Thread.run(Thread.java:841)`

Because of such errors the attachments are linked to the email with no contents or are not linked at all.

**It has to be remarked that the problem only occurs on Android devices - iOS tablets seem to work fine - and was replicated on tablets equipped with versions 4.4.2 and 5.0.2 .**

Cordova: 6.1.1
Cordova Android: 5.1.1

Thanks in advance and see you soon !

**Comment by Murthy582** [comment]
I'm also getting similar error, when I tried to attach file to gmail it is saying "permission denied for the attachment".

**Comment by Xavierh95** [comment]
I'm getting the same error with a Ionic project. Only on Android devices. Everything is OK for iOS.

Cordova CLI: 6.0.0
Cordova Android: 5.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.0-nightly-1823
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5

**Comment by sananoussa** [comment]
hi guys, I have the same problem, is there any updates about this issue ?
all what I could find is :

"GMail 5.0 added some security checks to attachments it receives from an Intent. These are unrelated to unix permissions, so the fact that the file is readable doesn't matter."

here http://stackoverflow.com/questions/26883259/gmail-5-0-app-fails-with-permission-denied-for-the-attachment-when-it-receives

**Comment by Xavierh95** [comment]
In order to bypass this issue, I encore my file content in base64, and everything is working now.

I have used https://github.com/ninjatronic/angular-base64 and did the following : 

```
$scope.shareWithEmail = function(subject, message, file_content){
    var file = null;
    if(file_content != undefined){
        file = "base64:contact.vcf//"+$base64.encode(file_content);
    }

    var email_obj = {
      subject: subject,
      body: message,
      isHtml:false,
      attachments:file
    };

    cordova.plugins.email.open(email_obj);
}

```

**Comment by brunodeprez** [comment]
+1 facing this issue, Xavierh95 solution solved the problem for the moment

**Comment by katzer** [comment]
Might be related to #198
