### ISSUE TITLE
Opening email with file attachment causes app crash on Android 8

### ISSUE THREAD

**Issue by dpa99c** [katzer/cordova-plugin-email-composer#270]
File access has been changed on Android 8, so using the current plugin implementation to attach a file to an email causing a crash on Android 8:

    09-11 20:29:34.703 14952-15146/io.cordova.hellocordova E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
     Process: io.cordova.hellocordova, PID: 14952
     android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/io.cordova.hellocordova/cache/email_composer/logo.png exposed beyond app through ClipData.Item.getUri()
         at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
         at android.net.Uri.checkFileUriExposed(Uri.java:2348)
         at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
         at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
         at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
         at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
         at android.app.Activity.startActivityForResult(Activity.java:4472)
         at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:342)
         at android.app.Activity.startActivityForResult(Activity.java:4430)
         at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:66)
         at de.martinreinhardt.cordova.plugins.email.EmailComposer$2.run(EmailComposer.java:155)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
         at java.lang.Thread.run(Thread.java:764)
         
         
To reproduce, just create a Cordova test project and run the example code on `deviceready` in Android 8 emulator/device:

    cordova.plugins.email.open({
        attachments: [
            'file://img/logo.png', //=> assets/www/img/logo.png (Android)
            'file://css/index.css' //=> www/css/index.css (iOS)
        ]
    });
    
The same code runs fine on Android 7.1.1 and below.

Seems there is a potential solution in [this SO post](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed).

**Comment by katzer** [comment]
@dpa99c Could you please let me know if it's working by installing the plugin from master?

**Comment by dpa99c** [comment]
@katzer Yes, this fixes it. Tested the master branch with Android 8.0 and it now works fine. 
Thanks for the quick turnaround time.

**Comment by thisIsChetan** [comment]
I was facing the same issue. But now it is working fine. Thank you @katzer

**Comment by katzer** [comment]
I've published v0.8.9
