### ISSUE TITLE
email composer android platform

### ISSUE THREAD

**Issue by fatihdurmaz** [katzer/cordova-plugin-email-composer#316]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yuumamobile.GYSMEB, PID: 26717
    java.lang.RuntimeException: Unable to get provider de.appplant.cordova.emailcomposer.Provider: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.emailcomposer.Provider" on path: DexPathList[[zip file "/data/app/com.yuumamobile.GYSMEB-2/base.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.yuumamobile.GYSMEB-2/lib/arm64, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6427)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6016)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5955)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6780)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.emailcomposer.Provider" on path: DexPathList[[zip file "/data/app/com.yuumamobile.GYSMEB-2/base.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.yuumamobile.GYSMEB-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.yuumamobile.GYSMEB-2/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6412)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6016) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5955) 
        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6780) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by FabianAlbrecht** [comment]
I only get this error when using the recently released version 7.1.3 of cordova-android.
With 7.1.2 everything works as expected.

**Comment by fatihdurmaz** [comment]
what should i do

**Comment by margsk** [comment]
Can I ask how you solved this issue.  I am getting the same error.
